name: Test Preprocessor
on: [push, pull_request]

env:
  GODOT_EXECUTABLE: Godot_v${{ vars.GODOT_VERSION }}_linux.x86_64

jobs:
  test-preprocessor:
    name: Test Preprocessor
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Godot
        id: cache-godot
        uses: actions/cache@v3
        env:
          cache-name: cache-godot
        with:
          path: ./${{ env.GODOT_EXECUTABLE }}
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ vars.GODOT_VERSION }}

      - if: ${{ steps.cache-godot.outputs.cache-hit != 'true' }}
        name: Install Godot
        run: |
          wget -q https://github.com/godotengine/godot-builds/releases/download/${{ vars.GODOT_VERSION }}/${{ env.GODOT_EXECUTABLE }}.zip
          unzip ${{ env.GODOT_EXECUTABLE }}.zip

      - name: Run tests
        run: |
          ./${{ env.GODOT_EXECUTABLE }} --headless -s test_runner.gd
